[package]
name = "editor"
description = "An Egui-based editor for the procedural_modelling crate"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bevy = { version = "^0.13.1", features = ["dynamic_linking"] }
bevy-inspector-egui = "^0.23.4"
bevy_panorbit_camera = { version = "^0.17.0", features = ["bevy_egui"] }

[dependencies.procedural_modelling]
path = "../"
features = ["bevy", "meshopt", "dynamic"]
