[package]
name = "fps_bench"
description = "A bevy-based fps benchmark"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bevy = { version = "^0.16.1", default-features = true }

[dependencies.procedural_modelling]
path = "../../"
features = ["bevy"]
