name: Rust

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
            - name: Install stable toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: Install Dependencies
              # alsa-sys deps: https://github.com/Spotifyd/spotifyd/issues/183#issuecomment-476384541
              # libudev-sys: https://github.com/hecrj/coffee/issues/119
              run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev libudev-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl1-mesa-dev xserver-xorg-dev libwayland-dev libwayland-cursor-dev libwayland-egl-backend-dev libegl1-mesa-dev
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
